### ISSUE TITLE
Nick and Ben's comments

### ISSUE THREAD

**Issue by MKLau** [HFpostdoc/SarrSens#37]

**Comment by amellison17** [comment]
Do you want to chat about Ben & Nick's comments? I should have some time Thursday before I leave for hiking on Friday.

**Comment by MKLau** [comment]
Yeah, that sounds good. I’ve been organizing them, I’ll send you the summary later this afternoon.

BTW - thanks for checking in on this.


On Jun 1, 2016, at 9:31 AM, Aaron Ellison <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want to chat about Ben & Nick's comments? I should have some time Thursday before I leave for hiking on Friday.

**Comment by MKLau** [comment]
I've added all of their comments as issues and added them to the manuscript as a commented field under the title
